- name: install open java
  yum:
    name: java-1.8.0-openjdk
    state: latest

- name: Download and install the public signing key
  shell: "rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch"

- name: Send elasticsearch.repo
  template:
    src: elasticsearch.repo.j2
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install elasticsearch Package
  yum:
    name: elasticsearch
    state: latest

- name: Send elasticsearch.yml
  template:
    src: "{{ mygroup_elasticsearch_yml }}"
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
    backup: yes

- name: get my ip address from hosts
  shell: "grep {{ ansible_eth0.ipv4.address }} /home/ansible/playbooks/ElasticStack/roles/elasticsearch_cluster/templates/el_hosts | awk -F' ' '{ print $2 }'"
  register: this_hostname
  delegate_to: localhost

- debug: var=this_hostname

- name: replace node name
  replace:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^node.name: .*\d{2}$'
    replace: 'node.name: {{ this_hostname.stdout }}'

- name: Send elasticsearchi-sysconfig
  template:
    src: elasticsearch-sysconfig.j2
    dest: /etc/sysconfig/elasticsearch
    owner: root
    group: elasticsearch
    mode: 0660
    backup: yes

- name: Send jvm file
  template:
    src: jvm.options
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: 0660
    backup: yes

- name: daemon-reload
  systemd:
    daemon_reload: yes

- name: es esrvice start
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
