- name: Send RPM
  copy:
    src: "{{ target_rpm }}"
    dest: /tmp/

- name: Install beat
  yum:
    name: "/tmp/{{ target_rpm }}"
    state: installed

- name: Send beat.yml
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: Start service
  service:
    name: metricbeat
    enabled: yes
    state: started

- name: Remove RPM
  shell: "rm -fr /tmp/{{ target_rpm }}"
