- name: Send RPM
  copy:
    src: "{{ item }}"
    dest: /tmp/
  with_items:
    - metricbeat-6.1.1-x86_64.rpm

- name: Install beat
  yum:
    name: "/tmp/{{ item }}"
    state: installed
  with_items:
    - metricbeat-6.1.1-x86_64.rpm

- name: Send beat.yml
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: Start service
  service:
    name: metricbeat
    enabled: yes
    state: started

- name: Remove RPM
  shell: "rm -fr /tmp/{{ item }}"
  with_items:
    - metricbeat-6.1.1-x86_64.rpm
