- name: Create host group
  local_action:
    module: zabbix_group
    server_url: "http://{{ zabbix_server_ipaddr }}/zabbix"
    login_user: "{{ zabbix_admin_user }}"
    login_password: "{{ zabbix_admin_password }}"
    state: present
    host_groups:
      - All_Templates

- name: Import Zabbix Template
  local_action:
    module: zabbix_template
    server_url: "http://{{ zabbix_server_ipaddr }}/zabbix"
    login_user: "{{ zabbix_admin_user }}"
    login_password: "{{ zabbix_admin_password }}"
##    template_name: "001_Tmpl_ALL_Alive_Ping"
    template_name: "{{ item.value.name }}"
##    template_json: "{{ lookup('file', '001_Tmpl_ALL_Alive_Ping.json') }}"
    template_json: "{{ item.value.file }}"
    template_groups:
      - All_Templates
    state: present
  with_dict:
      - "{{ template_list }}"
