- name: Send RPM
  copy:
    src: "{{ target_rpm }}"
    dest: /tmp/

- name: Install beat
  yum:
    name: "/tmp/{{ target_rpm }}"
    state: installed

- name: Send beat.yml
  template:
    src: heartbeat.yml.j2
    dest: /etc/heartbeat/heartbeat.yml
    owner: root
    group: root
    mode: 0600
    backup: yes

- name: Start service
  shell: "service heartbeat-elastic start"

- name: Remove RPM
  shell: "rm -fr /tmp/{{ target_rpm }}"
