- name: create server's directory
  local_action:
    module: file
    path: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}"
    state: directory
    owner: ansible
    group: ansible
    mode: 0755

- name: manage zabbix_agentd.conf
  fetch:
    src: /etc/zabbix/zabbix_agentd.conf
    dest: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}/zabbix_agentd.conf-{{ ansible_hostname }}"
    flat: yes
  ignore_errors: True

- name: manage filebeat
  fetch:
    src: /etc/filebeat/filebeat.yml
    dest: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}/filebeat.ym-{{ ansible_hostname }}"
    flat: yes
  ignore_errors: True

- name: manage metricbeat
  fetch:
    src: /etc/metricbeat/metricbeat.yml
    dest: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}/metricbeat.ym-{{ ansible_hostname }}"
    flat: yes
  ignore_errors: True
