- name: create server's directory
  local_action:
    module: file
    path: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}"
    state: directory
    owner: ansible
    group: ansible
    mode: 0755

- name: manage apache
  fetch:
    src: /etc/httpd/conf/httpd.conf
    dest: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}/httpd.conf-{{ ansible_hostname }}"
    flat: yes
  ignore_errors: True

- name: manage mysql
  fetch:
    src: /etc/my.cnf
    dest: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}/my.cnf-{{ ansible_hostname }}"
    flat: yes
  ignore_errors: True

- name: manage postfix main.cf
  fetch:
    src: /etc/postfix/main.cf
    dest: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}/postfix_main.cf-{{ ansible_hostname }}"
    flat: yes
  ignore_errors: True

- name: manage postfix master.cf
  fetch:
    src: /etc/postfix/master.cf
    dest: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}/postfix_master.cf-{{ ansible_hostname }}"
    flat: yes
  ignore_errors: True

- name: manage Clam AntiVirus freshclam.conf
  fetch:
    src: /etc/freshclam.conf
    dest: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}/freshclam.conf-{{ ansible_hostname }}"
    flat: yes
  ignore_errors: True

- name: manage zabbix_agentd.conf
  fetch:
    src: /etc/zabbix/zabbix_agentd.conf
    dest: "{{ home_conf_directory }}/remote/{{ ansible_hostname }}/zabbix_agentd.conf-{{ ansible_hostname }}"
    flat: yes
  ignore_errors: True
