- name: Launch instance
  ec2:
    key_name: "{{ keypair }}"
    group: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    count: "{{ create_num }}"
    instance_tags:
      Name: "{{ tagname_org }}"
  register: ec2
